# Generated by Django 4.2 on 2023-04-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheLoai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theloai',
            name='hien_thi_trang_chu',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
