# Generated by Django 4.2 on 2023-04-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TinTuc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tintuc',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='tin-tuc'),
        ),
    ]
