# Generated by Django 4.1.7 on 2023-03-23 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TheLoai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=500)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='')),
                ('gia', models.FloatField(blank=True, default=0, null=True)),
                ('don_vi_tien', models.CharField(blank=True, default='VND', max_length=10, null=True)),
                ('mo_ta_ngan', models.TextField(blank=True, null=True)),
                ('mo_ta_dai', models.TextField(blank=True, null=True)),
                ('the_loai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheLoai.theloai')),
            ],
        ),
    ]
