# Generated by Django 4.1.7 on 2023-03-24 03:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('SanPham', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='mo_ta_dai',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
