# Generated by Django 4.1.7 on 2023-03-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SanPham', '0002_alter_sanpham_mo_ta_dai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='san-pham'),
        ),
    ]
