# Generated by Django 4.1.7 on 2023-03-24 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SanPham', '0003_alter_sanpham_hinh_anh'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPhamNoiBat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_noi_bat', models.PositiveIntegerField(default=0)),
                ('san_pham', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SanPham.sanpham')),
            ],
        ),
    ]
