# Generated by Django 4.1.7 on 2023-03-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SanPham', '0005_alter_sanphamnoibat_san_pham'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='ngay_tao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
