# Generated by Django 4.2 on 2023-04-08 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TheLoai', '0002_theloai_hien_thi_trang_chu'),
        ('SanPham', '0006_sanpham_ngay_tao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='the_loai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='san_phams', to='TheLoai.theloai'),
        ),
    ]
