# Generated by Django 4.2 on 2023-04-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideTrangChu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='giao-dien')),
            ],
        ),
    ]
