# Generated by Django 4.2 on 2023-04-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GiaoDien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HinhTrangGioiThieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='giao-dien')),
            ],
        ),
        migrations.CreateModel(
            name='HinhTrangLienHe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='giao-dien')),
            ],
        ),
    ]
